### PR TITLE
fix: Xcode 12 compiling issues

### LINKED ISSUE #931: Fix issues related to the new Xcode 12
## Description
Beagle for iOS is not compiling in Xcode 12. There's a problem with the Starscream dependency that should be updated and another problem with the function builder implementation.

## Steps To Reproduce
1. Just try to compile the code and run the tests

## Expected Results
The project and tests should run normally

### PR DESCRIPTION
**Pull request by caioortu**
### Important

We added a `#if swift(<5.3)` compiler condition in some `init` that used **Function Builders**, because in swift _5.3_ we don't need to have `ChildrenBuilder` _and_ `ChildBuilder`, now with only `ChildrenBuilder` we can handle both _single_ parameter and _multiple_ parameters.
So, to still make our code compatible with previous swift versions, we will include that if statement in our code.

### Related Issues

Closes #931 

### Checklist

Please, check if these important points are met using `[x]`:

- [x] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [x] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [x] I am willing to follow-up on review comments in a timely manner.

### CODE REVIEW

**Comment by botbeaglezup** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">The title of PR not follow the rules of: https://www.conventionalcommits.org/en/v1.0.0/</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by caioortu** [comment]
As of today, September 21st, the changes in this PR fix all the issues related to Xcode 12 running our project. This is set as a `Work in Progress` just because the PR should be merged only when everyone starts using the new Xcode.

**Comment by theffc** [comment]
@caioortu about those `init` with `#if swift(<5.3)`, I couldn't figure out why we need them now 😅 can you help me with some context on that?

**Comment by caioortu** [comment]
> @caioortu about those `init` with `#if swift(<5.3)`, I couldn't figure out why we need them now 😅 can you help me with some context on that?

This is necessary due to a `function builder` bug that was fixed in swift 5.3. Before the correction, we needed an additional builder to handle one parameter cases, but after the correction having these two builder confuses the compiler making it unable to build.

**Review by theffc — APPROVED** [review]

**Review by lucasaraujo — APPROVED** [review]

**Review by dantes-git — APPROVED** [review]

**Review by victorrabelozup — APPROVED** [review]

**Pull request merged**
