### PR TITLE
Correction in typo

### PR DESCRIPTION
**Pull request by sasmitnalkande888**
### Checklist

Please, check if these important points are met using `[x]`:

- [ ] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [ ] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [ ] I am willing to follow-up on review comments in a timely manner.
- [ ] I have made the documentation changes or I created an issue explaining how to document this change on [Docs issues](https://github.com/ZupIT/beagle-docs/issues). Please link the issue here:

[PR Guide]: https://github.com/ZupIT/beagle/blob/main/doc/contributing/pull_requests.md

### CODE REVIEW

**Comment by uziassantosferreira** [comment]
@hectorcustodiozup and @carlossteinzup this PR was not evaluated either, and the commit was not signed, what do you think about guiding the user and closing this PR since the readme has already been changed?

**Comment by uziassantosferreira** [comment]
@otaviojava Wouldn't it be nice for some deadline for the RP for external contributions to be seen and that kind of thing doesn't happen here?

**Comment by hectorcustodiozup** [comment]
Hi @uziassantosferreira thank you for your interest in contributing with Beagle.

Our pull requests have template and guidelines marked on them to guide users, as well as our CONTRIBUTING file and documentation.

We are currently working on an automation for newly opened issues and pull requests.

This pull request will be reviewed as soon as the author applies the requirements.

**Comment by hectorcustodiozup** [comment]
Action: Closing
Reason: Inactivity (This pull request has been opened for three months and remained without updates or interaction from the author of the thread.)

If the author wishes it can be reopened and once addressed according to our contributing guidelines it will be reviewed

**Pull request closed without merging**
